/**
 * Phase 01: PR Lifecycle Foundation — Plan 01: PR Column and Draft PR Creation
 *
 * Tests verify must_haves from 01-01-PLAN.md
 * Generated by vit-test-writer after phase execution
 *
 * These files are markdown command/workflow documents, not TypeScript modules.
 * Tests verify their content matches the promises made in must_haves:
 *   - artifacts: files exist and contain required strings
 *   - key_links:  critical patterns are present
 *   - truths:     observable content-level behaviors
 */
import { describe, it, expect, beforeAll } from 'vitest'
import { readFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'

const WORK_DIR = join(import.meta.dirname, '..', '..', '..')

function read(relPath: string): string {
  const abs = join(WORK_DIR, relPath)
  if (!existsSync(abs)) {
    throw new Error(`File not found: ${abs}`)
  }
  return readFileSync(abs, 'utf8')
}

function exists(relPath: string): boolean {
  return existsSync(join(WORK_DIR, relPath))
}

// ---------------------------------------------------------------------------
// Artifact: .claude/vit/templates/state.md
// ---------------------------------------------------------------------------

describe('Phase 01-01: PR Column and Draft PR Creation', () => {
  describe('Artifact: .claude/vit/templates/state.md', () => {
    let content: string

    beforeAll(() => {
      content = read('.claude/vit/templates/state.md')
    })

    it('file exists', () => {
      expect(exists('.claude/vit/templates/state.md')).toBe(true)
    })

    it('contains PR column header in GitHub Issue Mapping table', () => {
      expect(content).toContain('| PR |')
    })

    it('documents the em-dash initial state (no PR yet)', () => {
      expect(content).toMatch(/—.*No PR created yet|—.*em.dash/i)
    })

    it('documents pr#N state (draft PR created)', () => {
      expect(content).toMatch(/pr#N.*Draft PR created|`pr#N`/)
    })

    it('documents pr#N(ready) state (promoted)', () => {
      expect(content).toMatch(/pr#N\(ready\)/)
    })

    it('documents pr:skipped state (gh CLI unavailable)', () => {
      expect(content).toMatch(/pr:skipped/)
    })

    it('File Template code block includes the PR column in the example table', () => {
      // The template's code block must show the table with a PR column
      expect(content).toMatch(/\| Phase \| Feature Issue \| Branch \| PR \|/)
    })
  })

  // ---------------------------------------------------------------------------
  // Artifact parity: files/ copy must be identical to .claude/ copy
  // ---------------------------------------------------------------------------

  describe('Artifact parity: .claude/ and files/ copies are identical', () => {
    it('.claude/vit/templates/state.md === files/vit/templates/state.md', () => {
      const a = read('.claude/vit/templates/state.md')
      const b = read('files/vit/templates/state.md')
      expect(a).toBe(b)
    })

    it('.claude/commands/vit/new-milestone.md === files/commands/vit/new-milestone.md', () => {
      const a = read('.claude/commands/vit/new-milestone.md')
      const b = read('files/commands/vit/new-milestone.md')
      expect(a).toBe(b)
    })

    it('.claude/commands/vit/execute-phase.md === files/commands/vit/execute-phase.md', () => {
      const a = read('.claude/commands/vit/execute-phase.md')
      const b = read('files/commands/vit/execute-phase.md')
      expect(a).toBe(b)
    })

    it('.claude/vit/workflows/execute-phase.md === files/vit/workflows/execute-phase.md', () => {
      const a = read('.claude/vit/workflows/execute-phase.md')
      const b = read('files/vit/workflows/execute-phase.md')
      expect(a).toBe(b)
    })
  })

  // ---------------------------------------------------------------------------
  // Artifact: .claude/commands/vit/new-milestone.md
  // ---------------------------------------------------------------------------

  describe('Artifact: .claude/commands/vit/new-milestone.md', () => {
    let content: string

    beforeAll(() => {
      content = read('.claude/commands/vit/new-milestone.md')
    })

    it('file exists', () => {
      expect(exists('.claude/commands/vit/new-milestone.md')).toBe(true)
    })

    it('contains PR column header in GitHub Issue Mapping table creation', () => {
      expect(content).toContain('| PR |')
    })

    it('initializes PR column to em-dash', () => {
      // The table row template must have | — | as the PR initial value
      expect(content).toMatch(/\| — \|/)
    })

    it('print summary table also contains PR column', () => {
      // The summary table printed to user must also include PR column
      const prColumnOccurrences = (content.match(/\| PR \|/g) ?? []).length
      expect(prColumnOccurrences).toBeGreaterThanOrEqual(2)
    })
  })

  // ---------------------------------------------------------------------------
  // Artifact: .claude/commands/vit/execute-phase.md
  // ---------------------------------------------------------------------------

  describe('Artifact: .claude/commands/vit/execute-phase.md — draft PR creation step', () => {
    let content: string

    beforeAll(() => {
      content = read('.claude/commands/vit/execute-phase.md')
    })

    it('file exists', () => {
      expect(exists('.claude/commands/vit/execute-phase.md')).toBe(true)
    })

    it('contains gh pr create --draft', () => {
      expect(content).toContain('gh pr create --draft')
    })

    it('MILESTONE_BRANCH variable is assigned to milestone/ prefix', () => {
      // The --base flag uses $MILESTONE_BRANCH, which is assigned as milestone/${MILESTONE}
      expect(content).toMatch(/MILESTONE_BRANCH="milestone\//)
    })

    it('--base flag uses the milestone branch variable', () => {
      expect(content).toMatch(/--base "\$MILESTONE_BRANCH"/)
    })

    it('idempotency guard uses gh pr list --head', () => {
      expect(content).toMatch(/gh pr list.*--head/)
    })

    it('PR body includes "Closes #" for feature issue link', () => {
      expect(content).toContain('Closes #')
    })

    it('records pr:skipped when gh CLI is unavailable', () => {
      expect(content).toContain('pr:skipped')
    })

    it('records pr#N in STATE.md after successful PR creation', () => {
      expect(content).toMatch(/pr#\$\{PR_NUM\}|pr#.*PR_NUM/)
    })

    it('step 0.7 is positioned between step 0.5 and step 1', () => {
      const step05Pos = content.indexOf('0.5.')
      const step07Pos = content.indexOf('0.7.')
      const step1Pos = content.indexOf('\n1. ')
      expect(step05Pos).toBeGreaterThan(-1)
      expect(step07Pos).toBeGreaterThan(step05Pos)
      expect(step1Pos).toBeGreaterThan(step07Pos)
    })

    it('PR creation is non-blocking — falls through on failure', () => {
      // Must have a continuation signal: "Continue to step 1" or similar
      expect(content).toMatch(/Continue to step 1|non-blocking/i)
    })

    it('PR title uses conventional commits format feat(phase-N)', () => {
      expect(content).toMatch(/feat\(phase-/)
    })
  })

  // ---------------------------------------------------------------------------
  // Artifact: .claude/vit/workflows/execute-phase.md
  // ---------------------------------------------------------------------------

  describe('Artifact: .claude/vit/workflows/execute-phase.md — create_draft_pr step', () => {
    let content: string

    beforeAll(() => {
      content = read('.claude/vit/workflows/execute-phase.md')
    })

    it('file exists', () => {
      expect(exists('.claude/vit/workflows/execute-phase.md')).toBe(true)
    })

    it('contains create_draft_pr step', () => {
      expect(content).toContain('create_draft_pr')
    })

    it('contains gh pr create --draft', () => {
      expect(content).toContain('gh pr create --draft')
    })

    it('idempotency guard via gh pr list --head', () => {
      expect(content).toMatch(/gh pr list.*--head/)
    })

    it('targets milestone/ base branch', () => {
      expect(content).toMatch(/milestone\//)
    })

    it('documents pr:skipped fallback', () => {
      expect(content).toContain('pr:skipped')
    })

    it('documents PR column values (—, pr#N, pr#N(ready), pr:skipped)', () => {
      expect(content).toContain('pr#N')
      expect(content).toContain('pr#N(ready)')
      expect(content).toContain('pr:skipped')
    })
  })

  // ---------------------------------------------------------------------------
  // Truth: STATE.md PR column value progression is documented
  // ---------------------------------------------------------------------------

  describe('Truth: STATE.md PR column value schema is complete', () => {
    it('template documents all four PR column states', () => {
      const content = read('.claude/vit/templates/state.md')
      // All four values must be present somewhere in the file
      expect(content).toMatch(/—.*em.dash|—.*No PR/i)
      expect(content).toMatch(/`pr#N`|pr#N.*Draft/)
      expect(content).toMatch(/pr#N\(ready\)/)
      expect(content).toMatch(/pr:skipped/)
    })
  })

  // ---------------------------------------------------------------------------
  // Key link: execute-phase writes pr#N to STATE.md PR column
  // ---------------------------------------------------------------------------

  describe('Key link: execute-phase -> STATE.md PR column update', () => {
    let content: string

    beforeAll(() => {
      content = read('.claude/commands/vit/execute-phase.md')
    })

    it('execute-phase updates STATE.md with pr#N pattern after creation', () => {
      expect(content).toMatch(/pr#\$\{PR_NUM\}|sed.*pr#/)
    })

    it('execute-phase reads DESIGNATED_BRANCH from STATE.md for idempotency', () => {
      expect(content).toContain('DESIGNATED_BRANCH')
      expect(content).toMatch(/gh pr list.*DESIGNATED_BRANCH|DESIGNATED_BRANCH.*gh pr list/)
    })
  })
})
