/**
 * Phase 01: PR Lifecycle Foundation — Plan 02: PR Promotion in verify-work
 *
 * Tests verify must_haves from 01-02-PLAN.md
 * Generated by vit-test-writer after phase execution
 *
 * These files are markdown command/workflow documents, not TypeScript modules.
 * Tests verify their content matches the promises made in must_haves:
 *   - artifacts: files exist and contain required strings
 *   - key_links:  critical patterns are present
 *   - truths:     observable content-level behaviors
 */
import { describe, it, expect, beforeAll } from 'vitest'
import { readFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'

const WORK_DIR = join(import.meta.dirname, '..', '..', '..')

function read(relPath: string): string {
  const abs = join(WORK_DIR, relPath)
  if (!existsSync(abs)) {
    throw new Error(`File not found: ${abs}`)
  }
  return readFileSync(abs, 'utf8')
}

function exists(relPath: string): boolean {
  return existsSync(join(WORK_DIR, relPath))
}

// ---------------------------------------------------------------------------
// Artifact: .claude/commands/vit/verify-work.md
// ---------------------------------------------------------------------------

describe('Phase 01-02: PR Promotion in verify-work', () => {
  describe('Artifact: .claude/commands/vit/verify-work.md — PR promotion step', () => {
    let content: string

    beforeAll(() => {
      content = read('.claude/commands/vit/verify-work.md')
    })

    it('file exists', () => {
      expect(exists('.claude/commands/vit/verify-work.md')).toBe(true)
    })

    it('contains gh pr ready command', () => {
      expect(content).toContain('gh pr ready')
    })

    it('PR promotion is gated to Route A only', () => {
      expect(content).toMatch(/Route A only|Route A \(all pass/)
    })

    it('Route B (all pass, last phase) is explicitly excluded from promotion', () => {
      expect(content).toMatch(/Route B.*[Ss]kip|[Ss]kip.*Route B|last phase.*[Ss]kip|[Ss]kip.*last phase/i)
    })

    it('Routes C and D (issues found) are explicitly excluded from promotion', () => {
      expect(content).toMatch(/Route C|issues > 0|issues.*0/i)
    })

    it('PR number is looked up from STATE.md PR column using grep pr#', () => {
      expect(content).toMatch(/grep.*pr#|PR_ENTRY.*STATE/)
    })

    it('STATE.md is updated from pr#N to pr#N(ready) after promotion', () => {
      expect(content).toMatch(/pr#.*ready|pr#\$\{PR_NUM\}\(ready\)/)
    })

    it('graceful skip when gh CLI is unavailable', () => {
      expect(content).toContain('PR promotion skipped')
    })

    it('promotion failure logs one line and continues (non-blocking)', () => {
      expect(content).toMatch(/PR promotion failed|non-blocking/i)
    })

    it('step 8.5 is positioned between step 8 and step 9', () => {
      const step8Pos = content.indexOf('8. ')
      const step85Pos = content.indexOf('8.5.')
      const step9Pos = content.indexOf('9. ')
      expect(step8Pos).toBeGreaterThan(-1)
      expect(step85Pos).toBeGreaterThan(step8Pos)
      expect(step9Pos).toBeGreaterThan(step85Pos)
    })

    it('uses gh pr ready (not gh pr review --approve)', () => {
      // Must use gh pr ready, not review --approve for promotion
      expect(content).toContain('gh pr ready')
      expect(content).not.toMatch(/gh pr review.*--approve/)
    })

    it('sed updates STATE.md pr#N to pr#N(ready) only after confirmed success', () => {
      // sed must run after PR_PROMOTED=true check
      expect(content).toMatch(/PR_PROMOTED=true[\s\S]*?sed|sed.*pr#.*ready/)
    })
  })

  // ---------------------------------------------------------------------------
  // Artifact: .claude/vit/workflows/verify-work.md
  // ---------------------------------------------------------------------------

  describe('Artifact: .claude/vit/workflows/verify-work.md — promote_pr step', () => {
    let content: string

    beforeAll(() => {
      content = read('.claude/vit/workflows/verify-work.md')
    })

    it('file exists', () => {
      expect(exists('.claude/vit/workflows/verify-work.md')).toBe(true)
    })

    it('contains promote_pr step', () => {
      expect(content).toContain('promote_pr')
    })

    it('contains gh pr ready', () => {
      expect(content).toContain('gh pr ready')
    })

    it('Route A only gate documented in workflow', () => {
      expect(content).toMatch(/Route A only|Route A \(all pass/)
    })

    it('documents pr:skipped / no-PR skip behavior', () => {
      expect(content).toMatch(/pr:skipped|No draft PR/)
    })

    it('promote_pr step definition comes after complete_session step definition', () => {
      // Use step name tags to find step positions (not inline references)
      const completePos = content.indexOf('<step name="complete_session">')
      const promotePos = content.indexOf('<step name="promote_pr">')
      expect(completePos).toBeGreaterThan(-1)
      expect(promotePos).toBeGreaterThan(completePos)
    })

    it('promote_pr step definition comes before diagnose_issues step definition', () => {
      // Use step name tags to find step positions (not inline references)
      const promotePos = content.indexOf('<step name="promote_pr">')
      const diagnosePos = content.indexOf('<step name="diagnose_issues">')
      expect(promotePos).toBeGreaterThan(-1)
      expect(diagnosePos).toBeGreaterThan(promotePos)
    })
  })

  // ---------------------------------------------------------------------------
  // Artifact parity: files/ copies must be identical to .claude/ copies
  // ---------------------------------------------------------------------------

  describe('Artifact parity: .claude/ and files/ copies are identical', () => {
    it('.claude/commands/vit/verify-work.md === files/commands/vit/verify-work.md', () => {
      const a = read('.claude/commands/vit/verify-work.md')
      const b = read('files/commands/vit/verify-work.md')
      expect(a).toBe(b)
    })

    it('.claude/vit/workflows/verify-work.md === files/vit/workflows/verify-work.md', () => {
      const a = read('.claude/vit/workflows/verify-work.md')
      const b = read('files/vit/workflows/verify-work.md')
      expect(a).toBe(b)
    })
  })

  // ---------------------------------------------------------------------------
  // Truth: verify-work promotes on Route A, leaves draft on B/C/D
  // ---------------------------------------------------------------------------

  describe('Truth: PR promotion route logic', () => {
    let commandContent: string
    let workflowContent: string

    beforeAll(() => {
      commandContent = read('.claude/commands/vit/verify-work.md')
      workflowContent = read('.claude/vit/workflows/verify-work.md')
    })

    it('command: Route A (all pass + more phases) triggers gh pr ready', () => {
      expect(commandContent).toMatch(/Route A/)
      expect(commandContent).toContain('gh pr ready')
    })

    it('command: Route B (all pass, last phase) explicitly skips promotion', () => {
      expect(commandContent).toMatch(/Route B.*[Ss]kip|last phase.*[Ss]kip|[Ss]kip.*last phase/i)
    })

    it('command: issues > 0 (Routes C/D) explicitly skips promotion', () => {
      expect(commandContent).toMatch(/issues > 0|Route C|Route D/i)
    })

    it('workflow: same Route A gate present in promote_pr step', () => {
      expect(workflowContent).toMatch(/Route A/)
      expect(workflowContent).toContain('gh pr ready')
    })
  })

  // ---------------------------------------------------------------------------
  // Truth: STATE.md PR column updates from pr#N to pr#N(ready) after promotion
  // ---------------------------------------------------------------------------

  describe('Truth: STATE.md PR column state transition after promotion', () => {
    it('command documents the pr#N -> pr#N(ready) transition via sed', () => {
      const content = read('.claude/commands/vit/verify-work.md')
      // sed command must turn pr#N into pr#N(ready)
      expect(content).toMatch(/sed.*pr#.*ready|s\/pr#\$\{PR_NUM\}\/pr#\$\{PR_NUM\}\(ready\)/)
    })

    it('workflow documents the pr#N -> pr#N(ready) transition', () => {
      const content = read('.claude/vit/workflows/verify-work.md')
      expect(content).toMatch(/pr#N.*ready|pr#\$\{PR_NUM\}\(ready\)/)
    })
  })

  // ---------------------------------------------------------------------------
  // Key link: verify-work reads pr#N from STATE.md to find the PR
  // ---------------------------------------------------------------------------

  describe('Key link: verify-work -> STATE.md GitHub Issue Mapping -> gh pr ready', () => {
    it('command looks up PR entry from STATE.md using grep', () => {
      const content = read('.claude/commands/vit/verify-work.md')
      expect(content).toMatch(/grep.*pr#|PR_ENTRY.*STATE/)
    })

    it('command extracts numeric PR number from pr#N entry', () => {
      const content = read('.claude/commands/vit/verify-work.md')
      expect(content).toMatch(/grep -o '\[0-9\]\*'|PR_NUM.*PR_ENTRY|grep.*\[0-9\]/)
    })
  })

  // ---------------------------------------------------------------------------
  // Truth: gh CLI unavailability is graceful — no abort, one-line notice
  // ---------------------------------------------------------------------------

  describe('Truth: gh CLI unavailability is graceful — no abort', () => {
    it('command prints one-line notice and continues when gh unavailable', () => {
      const content = read('.claude/commands/vit/verify-work.md')
      expect(content).toMatch(/PR promotion skipped.*gh not available|gh not available.*PR promotion skipped/)
    })

    it('workflow also handles gh unavailability non-blockingly', () => {
      const content = read('.claude/vit/workflows/verify-work.md')
      expect(content).toMatch(/gh not available|GH_AVAILABLE=false/)
    })
  })
})
