/**
 * Phase 02: AI PR Reviewer — Plan 01: vit-pr-reviewer Agent Definition
 *
 * Tests verify must_haves from 02-01-PLAN.md
 * Generated by vit-test-writer after phase execution
 *
 * These files are markdown agent documents, not TypeScript modules.
 * Tests verify their content matches the promises made in must_haves:
 *   - artifacts: file exists with valid frontmatter
 *   - key_links:  critical gh CLI patterns are present
 *   - truths:     observable content-level behaviors
 */
import { describe, it, expect, beforeAll } from 'vitest'
import { readFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'

const WORK_DIR = join(import.meta.dirname, '..', '..', '..')
const AGENT_PATH = '.claude/agents/vit-pr-reviewer.md'

function read(relPath: string): string {
  const abs = join(WORK_DIR, relPath)
  if (!existsSync(abs)) {
    throw new Error(`File not found: ${abs}`)
  }
  return readFileSync(abs, 'utf8')
}

function exists(relPath: string): boolean {
  return existsSync(join(WORK_DIR, relPath))
}

// ---------------------------------------------------------------------------
// Artifact: .claude/agents/vit-pr-reviewer.md — file existence and frontmatter
// ---------------------------------------------------------------------------

describe('Phase 02-01: vit-pr-reviewer Agent Definition', () => {
  describe('Artifact: .claude/agents/vit-pr-reviewer.md exists with valid frontmatter', () => {
    let content: string

    beforeAll(() => {
      content = read(AGENT_PATH)
    })

    it('file exists', () => {
      expect(exists(AGENT_PATH)).toBe(true)
    })

    it('frontmatter has name: vit-pr-reviewer', () => {
      expect(content).toMatch(/^name:\s*vit-pr-reviewer/m)
    })

    it('frontmatter has description field', () => {
      expect(content).toMatch(/^description:/m)
    })

    it('frontmatter has tools field', () => {
      expect(content).toMatch(/^tools:/m)
    })

    it('frontmatter tools include Bash', () => {
      // tools: Bash, Read  (order may vary)
      expect(content).toMatch(/tools:.*Bash/m)
    })

    it('frontmatter tools include Read', () => {
      expect(content).toMatch(/tools:.*Read/m)
    })

    it('frontmatter has color field', () => {
      expect(content).toMatch(/^color:/m)
    })

    it('frontmatter is valid YAML block (starts and ends with ---)', () => {
      // The file should start with --- and have a closing ---
      expect(content).toMatch(/^---/)
      const afterFirst = content.indexOf('\n---', 3)
      expect(afterFirst).toBeGreaterThan(0)
    })
  })

  // ---------------------------------------------------------------------------
  // Key link: agent uses gh pr diff to fetch the diff
  // ---------------------------------------------------------------------------

  describe('Key link: agent fetches PR diff via gh pr diff', () => {
    let content: string

    beforeAll(() => {
      content = read(AGENT_PATH)
    })

    it('contains gh pr diff', () => {
      expect(content).toMatch(/gh pr diff/)
    })
  })

  // ---------------------------------------------------------------------------
  // Key link: agent posts body summary via gh pr review --comment
  // ---------------------------------------------------------------------------

  describe('Key link: agent posts body summary via gh pr review --comment', () => {
    let content: string

    beforeAll(() => {
      content = read(AGENT_PATH)
    })

    it('contains gh pr review with --comment flag', () => {
      expect(content).toMatch(/gh pr review.*--comment/)
    })
  })

  // ---------------------------------------------------------------------------
  // Key link: agent posts inline comments via gh api REST pulls/N/reviews
  // ---------------------------------------------------------------------------

  describe('Key link: agent posts inline comments via gh api REST endpoint', () => {
    let content: string

    beforeAll(() => {
      content = read(AGENT_PATH)
    })

    it('contains gh api call targeting pulls/.../reviews endpoint', () => {
      expect(content).toMatch(/gh api.*pulls.*reviews/)
    })
  })

  // ---------------------------------------------------------------------------
  // Truth: agent uses three severity tiers
  // ---------------------------------------------------------------------------

  describe('Truth: review uses three severity tiers (block-merge, should-fix, nit)', () => {
    let content: string

    beforeAll(() => {
      content = read(AGENT_PATH)
    })

    it('contains block-merge tier', () => {
      expect(content).toContain('block-merge')
    })

    it('contains should-fix tier', () => {
      expect(content).toContain('should-fix')
    })

    it('contains nit tier', () => {
      expect(content).toContain('nit')
    })
  })

  // ---------------------------------------------------------------------------
  // Truth: agent uses event COMMENT (not APPROVE or REQUEST_CHANGES)
  // ---------------------------------------------------------------------------

  describe('Truth: inline comments use event COMMENT, not APPROVE or REQUEST_CHANGES', () => {
    let content: string

    beforeAll(() => {
      content = read(AGENT_PATH)
    })

    it('contains "event": "COMMENT" for the REST API call', () => {
      expect(content).toMatch(/"event":\s*"COMMENT"/)
    })

    it('does NOT use --approve flag on gh pr review (outside anti_patterns warnings)', () => {
      // The anti_patterns section documents forbidden usage as "DO NOT use X".
      // Strip that section before checking — any remaining --approve on a gh pr review
      // line would be actual usage, not a warning.
      const withoutAntiPatterns = content.replace(/<anti_patterns>[\s\S]*?<\/anti_patterns>/g, '')
      const reviewApproveMatches = withoutAntiPatterns.match(/gh pr review.*--approve/)
      expect(reviewApproveMatches).toBeNull()
    })

    it('does NOT use --request-changes flag on gh pr review (outside anti_patterns warnings)', () => {
      const withoutAntiPatterns = content.replace(/<anti_patterns>[\s\S]*?<\/anti_patterns>/g, '')
      const reviewRequestChangesMatches = withoutAntiPatterns.match(/gh pr review.*--request-changes/)
      expect(reviewRequestChangesMatches).toBeNull()
    })

    it('any "event" value in bash code blocks is COMMENT (not APPROVE or REQUEST_CHANGES)', () => {
      // Extract bash code blocks and verify event values within them are all COMMENT
      // The agent documents "event": "APPROVE" only as a forbidden pattern in warnings,
      // never as an actual value in a code block.
      const bashCodeBlocks = [...content.matchAll(/```bash([\s\S]*?)```/g)].map(m => m[1])
      for (const block of bashCodeBlocks) {
        expect(block).not.toMatch(/"event":\s*"APPROVE"/)
        expect(block).not.toMatch(/"event":\s*"REQUEST_CHANGES"/)
      }
    })

    it('the actual gh api REST call uses event COMMENT', () => {
      // The real API call must have "event": "COMMENT"
      expect(content).toMatch(/"event":\s*"COMMENT"/)
    })
  })

  // ---------------------------------------------------------------------------
  // Truth: inline comments are capped at 5
  // ---------------------------------------------------------------------------

  describe('Truth: inline diff comments are capped at 5 to avoid GitHub API 422 errors', () => {
    let content: string

    beforeAll(() => {
      content = read(AGENT_PATH)
    })

    it('documents the cap of 5 inline comments', () => {
      // Must mention 5 somewhere in the inline comments constraints
      expect(content).toMatch(/(?:up to\s*)?5\s*(?:inline\s*)?comments?|Maximum\s*5/i)
    })
  })

  // ---------------------------------------------------------------------------
  // Truth: agent never modifies local files (read-only + GitHub posting)
  // ---------------------------------------------------------------------------

  describe('Truth: agent is read-only and must not modify local files', () => {
    let content: string

    beforeAll(() => {
      content = read(AGENT_PATH)
    })

    it('documents read-only constraint', () => {
      expect(content).toMatch(/read-only|MUST NOT modify.*local files/i)
    })
  })

  // ---------------------------------------------------------------------------
  // Truth: graceful error handling throughout
  // ---------------------------------------------------------------------------

  describe('Truth: all gh commands have graceful error handling', () => {
    let content: string

    beforeAll(() => {
      content = read(AGENT_PATH)
    })

    it('contains 2>/dev/null or || true for error suppression', () => {
      expect(content).toMatch(/2>\/dev\/null||| true/)
    })

    it('contains reviewer failure log message', () => {
      expect(content).toMatch(/\[reviewer:.*failed|reviewer.*failed/i)
    })
  })
})
