/**
 * Phase 02: AI PR Reviewer — Plan 02: Verify-Work Reviewer Wiring
 *
 * Tests verify must_haves from 02-02-PLAN.md
 * Generated by vit-test-writer after phase execution
 *
 * These files are markdown command/workflow documents, not TypeScript modules.
 * Tests verify their content matches the promises made in must_haves:
 *   - artifacts: files exist and contain required strings/patterns
 *   - key_links:  critical wiring between verify-work and vit-pr-reviewer
 *   - truths:     Route A gate, non-blocking spawn, model table entry
 */
import { describe, it, expect, beforeAll } from 'vitest'
import { readFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'

const WORK_DIR = join(import.meta.dirname, '..', '..', '..')

const COMMAND_PATH = '.claude/commands/vit/verify-work.md'
const COMMAND_FILES_PATH = 'files/commands/vit/verify-work.md'
const WORKFLOW_PATH = '.claude/vit/workflows/verify-work.md'
const WORKFLOW_FILES_PATH = 'files/vit/workflows/verify-work.md'

function read(relPath: string): string {
  const abs = join(WORK_DIR, relPath)
  if (!existsSync(abs)) {
    throw new Error(`File not found: ${abs}`)
  }
  return readFileSync(abs, 'utf8')
}

function exists(relPath: string): boolean {
  return existsSync(join(WORK_DIR, relPath))
}

// ---------------------------------------------------------------------------
// Artifact: .claude/commands/vit/verify-work.md — reviewer spawn step
// ---------------------------------------------------------------------------

describe('Phase 02-02: Verify-Work Reviewer Wiring', () => {
  describe('Artifact: .claude/commands/vit/verify-work.md references vit-pr-reviewer', () => {
    let content: string

    beforeAll(() => {
      content = read(COMMAND_PATH)
    })

    it('file exists', () => {
      expect(exists(COMMAND_PATH)).toBe(true)
    })

    it('references vit-pr-reviewer agent', () => {
      expect(content).toContain('vit-pr-reviewer')
    })

    it('contains step 8.6 for spawning the reviewer', () => {
      expect(content).toContain('8.6')
    })
  })

  // ---------------------------------------------------------------------------
  // Key link: verify-work command gates reviewer on PR_PROMOTED=true
  // ---------------------------------------------------------------------------

  describe('Key link: reviewer spawn is gated on PR_PROMOTED=true (Route A only)', () => {
    let content: string

    beforeAll(() => {
      content = read(COMMAND_PATH)
    })

    it('contains PR_PROMOTED variable reference', () => {
      expect(content).toContain('PR_PROMOTED')
    })

    it('reviewer spawn is gated on PR_PROMOTED=true', () => {
      // The gate condition must appear in proximity to vit-pr-reviewer
      expect(content).toMatch(/PR_PROMOTED.*vit-pr-reviewer|vit-pr-reviewer.*PR_PROMOTED/s)
    })

    it('documents that reviewer only runs on Route A', () => {
      // Should document Route A gate explicitly
      expect(content).toMatch(/Route A|PR_PROMOTED=true/i)
    })
  })

  // ---------------------------------------------------------------------------
  // Truth: reviewer failure is non-blocking in the command
  // ---------------------------------------------------------------------------

  describe('Truth: reviewer failure is non-blocking in verify-work command', () => {
    let content: string

    beforeAll(() => {
      content = read(COMMAND_PATH)
    })

    it('contains reviewer failure log message', () => {
      expect(content).toMatch(/reviewer failed.*continuing|reviewer.*failed/i)
    })
  })

  // ---------------------------------------------------------------------------
  // Artifact: .claude/vit/workflows/verify-work.md — model table and spawn step
  // ---------------------------------------------------------------------------

  describe('Artifact: .claude/vit/workflows/verify-work.md has vit-pr-reviewer in model table', () => {
    let content: string

    beforeAll(() => {
      content = read(WORKFLOW_PATH)
    })

    it('file exists', () => {
      expect(exists(WORKFLOW_PATH)).toBe(true)
    })

    it('contains vit-pr-reviewer in the model lookup table', () => {
      // The model table row: | vit-pr-reviewer | sonnet | sonnet | haiku |
      expect(content).toMatch(/vit-pr-reviewer.*sonnet.*sonnet.*haiku/)
    })
  })

  // ---------------------------------------------------------------------------
  // Artifact: .claude/vit/workflows/verify-work.md — spawn_reviewer step
  // ---------------------------------------------------------------------------

  describe('Artifact: .claude/vit/workflows/verify-work.md has spawn_reviewer step', () => {
    let content: string

    beforeAll(() => {
      content = read(WORKFLOW_PATH)
    })

    it('contains spawn_reviewer step', () => {
      expect(content).toContain('spawn_reviewer')
    })

    it('spawn_reviewer step references vit-pr-reviewer', () => {
      expect(content).toContain('vit-pr-reviewer')
    })

    it('spawn_reviewer is gated on PR_PROMOTED=true', () => {
      expect(content).toContain('PR_PROMOTED')
    })

    it('spawn_reviewer has non-blocking error handling', () => {
      expect(content).toMatch(/reviewer failed.*continuing|reviewer.*failed/i)
    })
  })

  // ---------------------------------------------------------------------------
  // Artifact parity: .claude/ and files/ copies are byte-identical
  // ---------------------------------------------------------------------------

  describe('Artifact parity: .claude/ and files/ copies are identical', () => {
    it('.claude/commands/vit/verify-work.md === files/commands/vit/verify-work.md', () => {
      const a = read(COMMAND_PATH)
      const b = read(COMMAND_FILES_PATH)
      expect(a).toBe(b)
    })

    it('.claude/vit/workflows/verify-work.md === files/vit/workflows/verify-work.md', () => {
      const a = read(WORKFLOW_PATH)
      const b = read(WORKFLOW_FILES_PATH)
      expect(a).toBe(b)
    })
  })

  // ---------------------------------------------------------------------------
  // Truth: reviewer does NOT spawn on Routes B, C, or D
  // ---------------------------------------------------------------------------

  describe('Truth: reviewer spawns only after Route A PR promotion (not B/C/D)', () => {
    let commandContent: string
    let workflowContent: string

    beforeAll(() => {
      commandContent = read(COMMAND_PATH)
      workflowContent = read(WORKFLOW_PATH)
    })

    it('verify-work command step 8.6 is placed after step 8.5 (promote PR)', () => {
      const step85Pos = commandContent.indexOf('8.5.')
      const step86Pos = commandContent.indexOf('8.6.')
      expect(step85Pos).toBeGreaterThan(-1)
      expect(step86Pos).toBeGreaterThan(step85Pos)
    })

    it('verify-work workflow spawn_reviewer step is after promote_pr step', () => {
      const promotePrPos = workflowContent.indexOf('promote_pr')
      const spawnReviewerPos = workflowContent.indexOf('spawn_reviewer')
      expect(promotePrPos).toBeGreaterThan(-1)
      expect(spawnReviewerPos).toBeGreaterThan(promotePrPos)
    })

    it('command step 8.6 gate explicitly references PR_PROMOTED=true', () => {
      expect(commandContent).toMatch(/PR_PROMOTED=true/)
    })

    it('workflow spawn_reviewer gate references PR_PROMOTED=true', () => {
      expect(workflowContent).toMatch(/PR_PROMOTED=true/)
    })
  })

  // ---------------------------------------------------------------------------
  // Key link: Task() call passes required context variables to reviewer
  // ---------------------------------------------------------------------------

  describe('Key link: Task() call passes PR_NUM, REPO, WORK_DIR, PHASE_NUM, PHASE_NAME', () => {
    let content: string

    beforeAll(() => {
      content = read(COMMAND_PATH)
    })

    it('Task call passes PR Number context', () => {
      expect(content).toMatch(/PR Number.*PR_NUM|PR_NUM/i)
    })

    it('Task call passes Repo context', () => {
      expect(content).toMatch(/Repo.*REPO|\bREPO\b/i)
    })

    it('Task call passes Working Directory context', () => {
      expect(content).toMatch(/Working Directory.*WORK_DIR|WORK_DIR/i)
    })

    it('Task call passes Phase Number context', () => {
      expect(content).toMatch(/Phase Number.*PHASE_NUM|PHASE_NUM/i)
    })

    it('Task call passes Phase Name context', () => {
      expect(content).toMatch(/Phase Name.*PHASE_NAME|PHASE_NAME/i)
    })

    it('Task call uses subagent_type="vit-pr-reviewer"', () => {
      expect(content).toMatch(/subagent_type.*vit-pr-reviewer/)
    })
  })
})
